let places : string[] = ["Madina", "Makkah", "Palestine", "Iraq", "Al-Aqsa"]
console.log("Original Array",places)
console.log("Sorted array in alphabetical order", [...places].sort())
console.log("Original Array",places)
console.log("reverse array in alphabetical order", [...places].sort().reverse())
console.log("Original Array",places)
places.reverse()
console.log("reverse the order of array", places)
places.reverse()
console.log("reverse again to get original array", places)
places.sort()
console.log("sorted array in alphabetical order", places)
places.reverse()
console.log("sorted array in reverse alphabetical order", places)
